import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        bc: {
          bg: "var(--bc-bg)",
          "bg-deep": "var(--bc-bg-deep)",
          surface: "var(--bc-surface)",
          "surface-soft": "var(--bc-surface-soft)",
          card: "var(--bc-card)",
          "card-elevated": "var(--bc-card-elevated)",
          border: "var(--bc-border)",
          "border-strong": "var(--bc-border-strong)",
          text: "var(--bc-text)",
          "text-soft": "var(--bc-text-soft)",
          "text-muted": "var(--bc-text-muted)",
          green: "var(--bc-green)",
          "green-soft": "var(--bc-green-soft)",
          "green-glow": "var(--bc-green-glow)",
          red: "var(--bc-red)",
          "red-soft": "var(--bc-red-soft)",
          "red-glow": "var(--bc-red-glow)",
          amber: "var(--bc-amber)",
          "amber-soft": "var(--bc-amber-soft)",
          "amber-glow": "var(--bc-amber-glow)",
          blue: "var(--bc-blue)",
          purple: "var(--bc-purple)",
        },
        budget: {
          background: "var(--budget-background)",
          card: "var(--budget-card)",
          "card-hover": "var(--budget-card-hover)",
          primary: "var(--budget-primary)",
          text: "var(--budget-text)",
          muted: "var(--budget-text-muted)",
          cat: "var(--budget-cat)",
          success: "var(--budget-success)",
          warning: "var(--budget-warning)",
          urgent: "var(--budget-urgent)",
          savings: "var(--budget-savings)",
          remaining: "var(--budget-remaining)",
          border: "var(--budget-border)",
          nav: "var(--budget-nav)",
          income: "var(--budget-income)",
          expense: "var(--budget-expense)",
        },
      },
      fontFamily: {
        sans: ["DM Sans", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Fraunces", "Georgia", "serif"],
      },
      borderRadius: {
        bc: "var(--bc-radius-md)",
        "bc-sm": "var(--bc-radius-sm)",
        "bc-md": "var(--bc-radius-md)",
        "bc-lg": "var(--bc-radius-lg)",
        "bc-xl": "var(--bc-radius-xl)",
      },
      boxShadow: {
        bc: "var(--budget-shadow)",
      },
    },
  },
  plugins: [],
} satisfies Config;